-- CAF-211: MedDRA Primary AEFI 

WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET ECHO ON
SPOOL 6_CAF-211.log
ALTER SESSION SET CURRENT_SCHEMA=CAEFISS_OWNER;

ALTER TABLE AEFI_MEDDRAS
ADD (
  PRIMARY_AEFI NUMBER(2, 0)
);
commit;

ALTER TABLE AEFI_MEDDRAS_AUD
ADD (
  PRIMARY_AEFI NUMBER(2, 0)
);
commit;

SPOOL OFF;
