
-- CAF-556 & CAF-557: Updated Tab Name & Issue Fields

WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET ECHO ON
SPOOL 14_CAF-556.log
ALTER SESSION SET CURRENT_SCHEMA=CAEFISS_OWNER;

-- New CD_AEFI_FIELDS

-- Case information
INSERT INTO CD_AEFI_FIELDS(ENGLISH_VALUE, FRENCH_VALUE, AEFI_TABS_ID, DATE_CREATED, USER_CREATED, DATE_UPDATED, USER_UPDATED, STATUS, VERSION, SORTORDER) 
VALUES ('Add new file', 'Ajouter un nouveau ficher', 1, SYSDATE, 'Super', NULL, NULL, 1, 0, 165);

-- Immunization Errors
INSERT INTO CD_AEFI_FIELDS(ENGLISH_VALUE, FRENCH_VALUE, AEFI_TABS_ID, DATE_CREATED, USER_CREATED, DATE_UPDATED, USER_UPDATED, STATUS, VERSION, SORTORDER) 
VALUES ('Immunization errors - LLT', 'Erreurs d''immunisation - LLT', 5, SYSDATE, 'Super', NULL, NULL, 1, 0, 771);
INSERT INTO CD_AEFI_FIELDS(ENGLISH_VALUE, FRENCH_VALUE, AEFI_TABS_ID, DATE_CREATED, USER_CREATED, DATE_UPDATED, USER_UPDATED, STATUS, VERSION, SORTORDER) 
VALUES ('Immunization errors - PT', 'Erreurs d''immunisation - PT', 5, SYSDATE, 'Super', NULL, NULL, 1, 0, 772);
INSERT INTO CD_AEFI_FIELDS(ENGLISH_VALUE, FRENCH_VALUE, AEFI_TABS_ID, DATE_CREATED, USER_CREATED, DATE_UPDATED, USER_UPDATED, STATUS, VERSION, SORTORDER) 
VALUES ('Immunization errors - SOC', 'Erreurs d''immunisation - SOC', 5, SYSDATE, 'Super', NULL, NULL, 1, 0, 773);

-- Previous AEFI
INSERT INTO CD_AEFI_FIELDS(ENGLISH_VALUE, FRENCH_VALUE, AEFI_TABS_ID, DATE_CREATED, USER_CREATED, DATE_UPDATED, USER_UPDATED, STATUS, VERSION, SORTORDER) 
VALUES ('Previous AEFI - LLT', 'MAPI antérieures - LLT', 6, SYSDATE, 'Super', NULL, NULL, 1, 0, 791);
INSERT INTO CD_AEFI_FIELDS(ENGLISH_VALUE, FRENCH_VALUE, AEFI_TABS_ID, DATE_CREATED, USER_CREATED, DATE_UPDATED, USER_UPDATED, STATUS, VERSION, SORTORDER) 
VALUES ('Previous AEFI - PT', 'MAPI antérieures - PT', 6, SYSDATE, 'Super', NULL, NULL, 1, 0, 792);
INSERT INTO CD_AEFI_FIELDS(ENGLISH_VALUE, FRENCH_VALUE, AEFI_TABS_ID, DATE_CREATED, USER_CREATED, DATE_UPDATED, USER_UPDATED, STATUS, VERSION, SORTORDER) 
VALUES ('Previous AEFI - SOC', 'MAPI antérieures - SOC', 6, SYSDATE, 'Super', NULL, NULL, 1, 0, 793);

-- AEFI IOC
INSERT INTO CD_AEFI_FIELDS(ENGLISH_VALUE, FRENCH_VALUE, AEFI_TABS_ID, DATE_CREATED, USER_CREATED, DATE_UPDATED, USER_UPDATED, STATUS, VERSION, SORTORDER) 
VALUES ('If required hospitalization - Days in ICU/NICU', 'Si l''hospitalisation requise - Jours aux soins intensifs / USIN', 7, SYSDATE, 'Super', NULL, NULL, 1, 0, 875);

-- Treatment
INSERT INTO CD_AEFI_FIELDS(ENGLISH_VALUE, FRENCH_VALUE, AEFI_TABS_ID, DATE_CREATED, USER_CREATED, DATE_UPDATED, USER_UPDATED, STATUS, VERSION, SORTORDER) 
VALUES ('Treatment - LLT', 'Traitement - LLT', 8, SYSDATE, 'Super', NULL, NULL, 1, 0, 911);
INSERT INTO CD_AEFI_FIELDS(ENGLISH_VALUE, FRENCH_VALUE, AEFI_TABS_ID, DATE_CREATED, USER_CREATED, DATE_UPDATED, USER_UPDATED, STATUS, VERSION, SORTORDER) 
VALUES ('Treatment - PT', 'Traitement - PT', 8, SYSDATE, 'Super', NULL, NULL, 1, 0, 912);
INSERT INTO CD_AEFI_FIELDS(ENGLISH_VALUE, FRENCH_VALUE, AEFI_TABS_ID, DATE_CREATED, USER_CREATED, DATE_UPDATED, USER_UPDATED, STATUS, VERSION, SORTORDER) 
VALUES ('Treatment - SOC', 'Traitement - SOC', 8, SYSDATE, 'Super', NULL, NULL, 1, 0, 913);

-- MedDRA
INSERT INTO CD_AEFI_FIELDS(ENGLISH_VALUE, FRENCH_VALUE, AEFI_TABS_ID, DATE_CREATED, USER_CREATED, DATE_UPDATED, USER_UPDATED, STATUS, VERSION, SORTORDER) 
VALUES ('Primary AEFI', 'MAPI principal', 15, SYSDATE, 'Super', NULL, NULL, 1, 0, 2019);
INSERT INTO CD_AEFI_FIELDS(ENGLISH_VALUE, FRENCH_VALUE, AEFI_TABS_ID, DATE_CREATED, USER_CREATED, DATE_UPDATED, USER_UPDATED, STATUS, VERSION, SORTORDER) 
VALUES ('HLT', 'HLT', 15, SYSDATE, 'Super', NULL, NULL, 1, 0, 2041);
INSERT INTO CD_AEFI_FIELDS(ENGLISH_VALUE, FRENCH_VALUE, AEFI_TABS_ID, DATE_CREATED, USER_CREATED, DATE_UPDATED, USER_UPDATED, STATUS, VERSION, SORTORDER) 
VALUES ('HLGT', 'HLGT', 15, SYSDATE, 'Super', NULL, NULL, 1, 0, 2042);

-- Follow Up
INSERT INTO CD_AEFI_FIELDS(ENGLISH_VALUE, FRENCH_VALUE, AEFI_TABS_ID, DATE_CREATED, USER_CREATED, DATE_UPDATED, USER_UPDATED, STATUS, VERSION, SORTORDER) 
VALUES ('Follow up - LLT', 'Suivi - LLT', 17, SYSDATE, 'Super', NULL, NULL, 1, 0, 2241);
INSERT INTO CD_AEFI_FIELDS(ENGLISH_VALUE, FRENCH_VALUE, AEFI_TABS_ID, DATE_CREATED, USER_CREATED, DATE_UPDATED, USER_UPDATED, STATUS, VERSION, SORTORDER) 
VALUES ('Follow up - PT', 'Suivi - PT', 17, SYSDATE, 'Super', NULL, NULL, 1, 0, 2242);
INSERT INTO CD_AEFI_FIELDS(ENGLISH_VALUE, FRENCH_VALUE, AEFI_TABS_ID, DATE_CREATED, USER_CREATED, DATE_UPDATED, USER_UPDATED, STATUS, VERSION, SORTORDER) 
VALUES ('Follow up - SOC', 'Suivi - SOC', 17, SYSDATE, 'Super', NULL, NULL, 1, 0, 2243);

-- Case Management 
INSERT INTO CD_AEFI_FIELDS(ENGLISH_VALUE, FRENCH_VALUE, AEFI_TABS_ID, DATE_CREATED, USER_CREATED, DATE_UPDATED, USER_UPDATED, STATUS, VERSION, SORTORDER) 
VALUES ('Follow-up - Follow-up assigned to', 'Suivi - Action Suivi assigné à', 20, SYSDATE, 'Super', NULL, NULL, 1, 0, 2599);
INSERT INTO CD_AEFI_FIELDS(ENGLISH_VALUE, FRENCH_VALUE, AEFI_TABS_ID, DATE_CREATED, USER_CREATED, DATE_UPDATED, USER_UPDATED, STATUS, VERSION, SORTORDER) 
VALUES ('Case issues - Resolution assigned to', 'Problèmes de cas et résolution - Résolution assignée à', 20, SYSDATE, 'Super', NULL, NULL, 1, 0, 2799);

 
-- Updated CD_AEFI_FIELDS  

-- Medical History Fields
UPDATE CD_AEFI_FIELDS
    SET ENGLISH_VALUE = 'Recent immunization history: Please indicate below any other vaccine(s) received within 30 days prior to the "date vaccine administered" reported in the Vaccine tab',
        FRENCH_VALUE = 'Historique récent de vaccination : Veuillez indiquer ci-dessous tout autre vaccin reçu dans les 30 jours précédant la « date d’administration du vaccin » indiquée dans l’onglet Vaccin.' 
    WHERE ENGLISH_VALUE = 'Recent immunization history: Please indicate below any other vaccine(s) received within 30 days prior to the "date vaccine administered" reported in section 4a'
    AND AEFI_TABS_ID = (SELECT ID FROM CD_AEFI_TABS WHERE ENGLISH_VALUE = 'Medical History');

-- Case Management Fields
UPDATE CD_AEFI_FIELDS
    SET ENGLISH_VALUE = 'Follow-up - Follow-up Issue field',
        FRENCH_VALUE = 'Suivi auprès - Champ du problème de suivi'
    WHERE ENGLISH_VALUE = 'Follow-up Issue field'
    AND AEFI_TABS_ID = (SELECT ID FROM CD_AEFI_TABS WHERE ENGLISH_VALUE = 'Case Management');

UPDATE CD_AEFI_FIELDS
    SET ENGLISH_VALUE = 'Follow-up - Follow-up issues type'
    WHERE ENGLISH_VALUE = 'Follow-up issues type'
    AND AEFI_TABS_ID = (SELECT ID FROM CD_AEFI_TABS WHERE ENGLISH_VALUE = 'Case Management');

UPDATE CD_AEFI_FIELDS
    SET ENGLISH_VALUE = 'Follow-up - Follow-up Status'
    WHERE ENGLISH_VALUE = 'Follow-up Status'
    AND AEFI_TABS_ID = (SELECT ID FROM CD_AEFI_TABS WHERE ENGLISH_VALUE = 'Case Management');

UPDATE CD_AEFI_FIELDS
    SET ENGLISH_VALUE = 'Follow-up - Follow-up resolved by'
    WHERE ENGLISH_VALUE = 'Follow-up resolved by'
    AND AEFI_TABS_ID = (SELECT ID FROM CD_AEFI_TABS WHERE ENGLISH_VALUE = 'Case Management');

-- MCR / Secondary Review Fields
UPDATE CD_AEFI_FIELDS
    SET ENGLISH_VALUE = 'Case Definition Used'
    WHERE ENGLISH_VALUE = 'Causality assessment question - Causality Assessment'
    AND AEFI_TABS_ID = (SELECT ID FROM CD_AEFI_TABS WHERE ENGLISH_VALUE = 'MCR / Secondary Review');

-- Updated CD_AEFI_TABS
UPDATE CD_AEFI_TABS
    SET STATUS = 0
    WHERE ENGLISH_VALUE IN ('MCR / Reviews', 'MCR / Eligibility for CA and classification', 'MCR / Medical History Other Cause', 'MCR / Known Causality Vaccine', 'MCR / Evidence Causality Association', 'MCR / Qualifying Factors');
    
-- Update user role for sys access
UPDATE SEC_USERS_ROLES
    SET ROLE_ID = 1
    WHERE USER_ID = (
        SELECT ID 
        FROM SEC_USERS 
        WHERE USERNAME = 'WallaceA'
);
   
commit;
SPOOL OFF

