-- CAF-213: Previous AEFI - Did this AEFI follow a previous dose of any of the immunizing agents entered in the "Vaccines" tab?
-- New CD value 

WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET ECHO ON
SPOOL 8_CAF-213.log
ALTER SESSION SET CURRENT_SCHEMA=CAEFISS_OWNER;

INSERT INTO CD_PREVIOUS_IMMUNIZING (ID, ENGLISH_VALUE, FRENCH_VALUE, DATE_CREATED, USER_CREATED, DATE_UPDATED, USER_UPDATED, STATUS, VERSION, SORTORDER) 
VALUES (10, 'Unspecified', 'Non Spécifié', SYSDATE, 'Super', NULL, NULL, 1, 0, 35);

commit;

SPOOL OFF
