-- CAF-205: AEFI impact, outcome, care obtained -highest level - new values

WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET ECHO ON
SPOOL 2_CAF-205.log
ALTER SESSION SET CURRENT_SCHEMA=CAEFISS_OWNER;

ALTER TABLE AEFI_HOSPITALIZATION
ADD (
  DAYS_ICU NUMBER(4)
);
commit;

ALTER TABLE AEFI_HOSPITALIZATION_AUD
ADD (
  DAYS_ICU NUMBER(4)
);
commit;

SPOOL OFF;
