-- CAF-209: Immunization errors -new values

WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET ECHO ON
SPOOL 5_CAF-209.log
ALTER SESSION SET CURRENT_SCHEMA=CAEFISS_OWNER;

INSERT INTO CD_INCORRECT_IMMUNIZATION (ID, ENGLISH_VALUE, FRENCH_VALUE, DATE_CREATED, USER_CREATED, DATE_UPDATED, USER_UPDATED, STATUS, VERSION, SORTORDER) 
VALUES (10, 'Unspecified', 'Non Spécifié', SYSDATE, 'Super', NULL, NULL, 1, 0, 0);

commit;

SPOOL OFF
