-- CAF-204: IOC - Outcome at time of report
-- New CD value 

WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET ECHO ON
SPOOL 1_CAF-204.log
ALTER SESSION SET CURRENT_SCHEMA=CAEFISS_OWNER;

INSERT INTO CD_OUTCOME (ID, ENGLISH_VALUE, FRENCH_VALUE, OUTCOME_ABBR_EN, OUTCOME_ABBR_FR, DATE_CREATED, USER_CREATED, DATE_UPDATED, USER_UPDATED, STATUS, VERSION, SORTORDER) 
VALUES (10, 'Congenital anomaly/birth defect', 'Anomalie congénitale / malformation à la naissance', 'CA', NULL, SYSDATE, 'Super', NULL, NULL, 1, 0, 25);

commit;

SPOOL OFF
