-- CAF-214: AEFI Treatment meddra

WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET ECHO ON
SPOOL 9_CAF-214.log
define _APP_USER_ROLE = rl__caefiss_app;
ALTER SESSION SET CURRENT_SCHEMA=CAEFISS_OWNER;

CREATE TABLE AEFI_TREATMENT
(
  ID	NUMBER(10) not NULL,
  AEFI_ID	NUMBER(10) not NULL,
  MEDDRA_ID	NUMBER(10) not NULL,
  VERBATIM	VARCHAR2(255 CHAR),
  ROW_DISPLAY_ORDER NUMBER(10),
  CONSTRAINT PK_AEFI_TREATMENT PRIMARY KEY (ID),
  CONSTRAINT FK_AEFI_TREATMENT_ID FOREIGN KEY(AEFI_ID) REFERENCES AEFI_FORM(ID),
  CONSTRAINT FK_AEFI_TREATMENT_MEDDRA_ID FOREIGN KEY(MEDDRA_ID) REFERENCES CD_MEDDRA(ID),
  CONSTRAINT UK_AEFI_TREATMENT	UNIQUE(AEFI_ID, MEDDRA_ID)
);

CREATE TABLE AEFI_TREATMENT_AUD
(
  ID	NUMBER(10),
  AEFI_ID	NUMBER(10),
  MEDDRA_ID	NUMBER(10),
  VERBATIM	VARCHAR2(255 CHAR),
  ROW_DISPLAY_ORDER NUMBER(10),
  REV            NUMBER(10),
  REVTYPE        NUMBER(3)
);

CREATE SEQUENCE AEFI_TREATMENT_ID_SEQ INCREMENT BY 1 START WITH 1 CACHE 2; 

GRANT INSERT, SELECT, UPDATE, DELETE ON CAEFISS_OWNER.AEFI_TREATMENT  TO &_APP_USER_ROLE;
GRANT INSERT, SELECT ON CAEFISS_OWNER.AEFI_TREATMENT_AUD TO &_APP_USER_ROLE;
GRANT SELECT, ALTER ON CAEFISS_OWNER.AEFI_TREATMENT_ID_SEQ TO &_APP_USER_ROLE;

CREATE INDEX IDX_AEFI_TR_AEFI_ID ON AEFI_TREATMENT(AEFI_ID);
CREATE INDEX IDX_AEFI_TR_MEDDRA_ID ON AEFI_TREATMENT(MEDDRA_ID);

commit;

SPOOL OFF
