-- CAF-316: CM - Follow-up - Issue Field

WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET ECHO ON
SPOOL 10_CAF-316.log
define _APP_USER_ROLE = rl__caefiss_app;
ALTER SESSION SET CURRENT_SCHEMA=CAEFISS_OWNER;

-- Add Issue Field Id to Follow Up
ALTER TABLE AEFI_QA_FOLLOWUP_FPT
ADD (
  ISSUES_FIELD_ID NUMBER(15),
  CONSTRAINT FK_AEFI_QA_FOLLOW_FPT_ISSUES_FIELD_ID FOREIGN KEY (ISSUES_FIELD_ID) REFERENCES CD_AEFI_FIELDS (ID)
);

ALTER TABLE AEFI_QA_FOLLOWUP_FPT_AUD
ADD (
  ISSUES_FIELD_ID NUMBER(15)
);
commit;

SPOOL OFF
