-- CAF-318: Update values for CD_ABORIGINAL_STATUS

WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET ECHO ON
SPOOL 11_CAF-318.log
ALTER SESSION SET CURRENT_SCHEMA=CAEFISS_OWNER;

-- Corrected vaues 
UPDATE CD_ABORIGINAL_STATUS
    SET ENGLISH_VALUE = CASE
        WHEN ID = 1 THEN 'First Nations'
        WHEN ID = 2 THEN 'Inuk/Inuit' 
        WHEN ID = 3 THEN 'Métis'
        WHEN ID = 4 THEN 'Other Indigenous'
        ELSE ENGLISH_VALUE
    END
WHERE ID IN (1, 2, 3, 4);

UPDATE CD_ABORIGINAL_STATUS
    SET FRENCH_VALUE = CASE
        WHEN ID = 1 THEN 'Premières Nations'
        WHEN ID = 2 THEN 'Inuk/Inuit' 
        WHEN ID = 3 THEN 'Métis'
        WHEN ID = 4 THEN 'Autre groupe autochtone'
        ELSE FRENCH_VALUE 
    END
WHERE ID IN (1, 2, 3, 4);

-- New values
INSERT INTO CD_ABORIGINAL_STATUS (ID, ENGLISH_VALUE, FRENCH_VALUE, DATE_CREATED, USER_CREATED, DATE_UPDATED, USER_UPDATED, STATUS, VERSION, SORTORDER) 
VALUES (10, 'Prefer not to answer', 'Préfère ne pas répondre', SYSDATE, 'Super', NULL, NULL, 1, 0, 0);

INSERT INTO CD_ABORIGINAL_STATUS (ID, ENGLISH_VALUE, FRENCH_VALUE, DATE_CREATED, USER_CREATED, DATE_UPDATED, USER_UPDATED, STATUS, VERSION, SORTORDER) 
VALUES (11, 'Not asked', 'Non demandé', SYSDATE, 'Super', NULL, NULL, 1, 0, 0);

INSERT INTO CD_ABORIGINAL_STATUS (ID, ENGLISH_VALUE, FRENCH_VALUE, DATE_CREATED, USER_CREATED, DATE_UPDATED, USER_UPDATED, STATUS, VERSION, SORTORDER) 
VALUES (12, 'Unspecified', 'Non précisé', SYSDATE, 'Super', NULL, NULL, 1, 0, 0);


UPDATE CD_ABORIGINAL_STATUS_AUD
    SET ENGLISH_VALUE = CASE
        WHEN ID = 1 THEN 'First Nations'
        WHEN ID = 2 THEN 'Inuk/Inuit' 
        WHEN ID = 3 THEN 'Métis'
        WHEN ID = 4 THEN 'Other Indigenous'
        ELSE ENGLISH_VALUE
    END
WHERE ID IN (1, 2, 3, 4);

UPDATE CD_ABORIGINAL_STATUS_AUD
    SET FRENCH_VALUE = CASE
        WHEN ID = 1 THEN 'Premières Nations'
        WHEN ID = 2 THEN 'Inuk/Inuit' 
        WHEN ID = 3 THEN 'Métis'
        WHEN ID = 4 THEN 'Autre groupe autochtone'
        ELSE FRENCH_VALUE 
    END
WHERE ID IN (1, 2, 3, 4);

INSERT INTO CD_ABORIGINAL_STATUS_AUD (ID, ENGLISH_VALUE, FRENCH_VALUE, DATE_CREATED, USER_CREATED, DATE_UPDATED, USER_UPDATED, STATUS, VERSION, SORTORDER) 
VALUES (10, 'Prefer not to answer', 'Préfère ne pas répondre', SYSDATE, 'Super', NULL, NULL, 1, 0, 0);

INSERT INTO CD_ABORIGINAL_STATUS_AUD (ID, ENGLISH_VALUE, FRENCH_VALUE, DATE_CREATED, USER_CREATED, DATE_UPDATED, USER_UPDATED, STATUS, VERSION, SORTORDER) 
VALUES (11, 'Not asked', 'Non demandé', SYSDATE, 'Super', NULL, NULL, 1, 0, 0);

INSERT INTO CD_ABORIGINAL_STATUS_AUD (ID, ENGLISH_VALUE, FRENCH_VALUE, DATE_CREATED, USER_CREATED, DATE_UPDATED, USER_UPDATED, STATUS, VERSION, SORTORDER) 
VALUES (12, 'Unspecified', 'Non précisé', SYSDATE, 'Super', NULL, NULL, 1, 0, 0);

commit;

SPOOL OFF;
