-- CAF-555: Immunization Error Checkbox Field

WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET ECHO ON
SPOOL 15_CAF-555.log
ALTER SESSION SET CURRENT_SCHEMA=CAEFISS_OWNER;
   
UPDATE CD_AEFI_FIELDS
    SET STATUS = 0
    WHERE ID = 77;
    
commit;

SPOOL OFF
