-- CAF-207: AEFI Immunization Error Meddra

WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET ECHO ON
SPOOL 4_CAF-207.log
ALTER SESSION SET CURRENT_SCHEMA=CAEFISS_OWNER;
define _APP_USER_ROLE = rl__caefiss_app;

CREATE TABLE AEFI_IMMUNIZATION_ERROR
(
  ID	NUMBER(10) not NULL,
  AEFI_ID	NUMBER(10) not NULL,
  MEDDRA_ID	NUMBER(10) not NULL,
  VERBATIM	VARCHAR2(255 CHAR),
  ROW_DISPLAY_ORDER NUMBER(10),
  CONSTRAINT PK_AEFI_IMMUNIZATION_ERROR PRIMARY KEY (ID),
  CONSTRAINT FK_AEFI_IMMUNIZATION_ERROR_ID FOREIGN KEY(AEFI_ID) REFERENCES AEFI_FORM(ID),
  CONSTRAINT FK_AEFI_IMMUNIZATION_ERROR_MEDDRA_ID FOREIGN KEY(MEDDRA_ID) REFERENCES CD_MEDDRA(ID),
  CONSTRAINT UK_AEFI_IMMUNIZATION_ERROR	UNIQUE(AEFI_ID, MEDDRA_ID)
);

CREATE TABLE AEFI_IMMUNIZATION_ERROR_AUD
(
  ID	NUMBER(10),
  AEFI_ID	NUMBER(10),
  MEDDRA_ID	NUMBER(10),
  VERBATIM	VARCHAR2(255 CHAR),
  ROW_DISPLAY_ORDER NUMBER(10),
  REV            NUMBER(10),
  REVTYPE        NUMBER(3)
);

CREATE SEQUENCE  AEFI_IMMUNIZATION_ERROR_ID_SEQ INCREMENT BY 1 START WITH 1 CACHE 2; 

GRANT INSERT, SELECT, UPDATE, DELETE ON CAEFISS_OWNER.AEFI_IMMUNIZATION_ERROR  TO &_APP_USER_ROLE;
GRANT INSERT, SELECT ON CAEFISS_OWNER.AEFI_IMMUNIZATION_ERROR_AUD TO &_APP_USER_ROLE;
GRANT SELECT, ALTER ON CAEFISS_OWNER.AEFI_IMMUNIZATION_ERROR_ID_SEQ TO &_APP_USER_ROLE;

CREATE INDEX IDX_AEFI_IE_AEFI_ID ON AEFI_IMMUNIZATION_ERROR(AEFI_ID);
CREATE INDEX IDX_AEFI_IE_MEDDRA_ID ON AEFI_IMMUNIZATION_ERROR(MEDDRA_ID);

commit;

SPOOL OFF
