-- To create private synonyms for new tables

SET ECHO ON 
SPOOL 12_create_private_synonyms.log 
WHENEVER SQLERROR CONTINUE;

DEFINE USER=CAEFISS_APP;
CREATE OR REPLACE SYNONYM &USER..AEFI_HOSPITALIZATION           FOR CAEFISS_OWNER.AEFI_HOSPITALIZATION;
CREATE OR REPLACE SYNONYM &USER..AEFI_HOSPITALIZATION_AUD       FOR CAEFISS_OWNER.AEFI_HOSPITALIZATION_AUD;

CREATE OR REPLACE SYNONYM &USER..AEFI_FOLLOW_UP                 FOR CAEFISS_OWNER.AEFI_FOLLOW_UP;
CREATE OR REPLACE SYNONYM &USER..AEFI_FOLLOW_UP_AUD             FOR CAEFISS_OWNER.AEFI_FOLLOW_UP_AUD;
CREATE OR REPLACE SYNONYM &USER..AEFI_FOLLOW_UP_ID_SEQ          FOR CAEFISS_OWNER.AEFI_FOLLOW_UP_ID_SEQ;

CREATE OR REPLACE SYNONYM &USER..AEFI_IMMUNIZATION_ERROR        FOR CAEFISS_OWNER.AEFI_IMMUNIZATION_ERROR;
CREATE OR REPLACE SYNONYM &USER..AEFI_IMMUNIZATION_ERROR_AUD    FOR CAEFISS_OWNER.AEFI_IMMUNIZATION_ERROR_AUD;
CREATE OR REPLACE SYNONYM &USER..AEFI_IMMUNIZATION_ERROR_ID_SEQ FOR CAEFISS_OWNER.AEFI_IMMUNIZATION_ERROR_ID_SEQ;

CREATE OR REPLACE SYNONYM &USER..AEFI_PREVIOUS_AEFI             FOR CAEFISS_OWNER.AEFI_PREVIOUS_AEFI;
CREATE OR REPLACE SYNONYM &USER..AEFI_PREVIOUS_AEFI_AUD         FOR CAEFISS_OWNER.AEFI_PREVIOUS_AEFI_AUD;
CREATE OR REPLACE SYNONYM &USER..AEFI_PREVIOUS_AEFI_ID_SEQ      FOR CAEFISS_OWNER.AEFI_PREVIOUS_AEFI_ID_SEQ;

CREATE OR REPLACE SYNONYM &USER..AEFI_TREATMENT                 FOR CAEFISS_OWNER.AEFI_TREATMENT;
CREATE OR REPLACE SYNONYM &USER..AEFI_TREATMENT_AUD             FOR CAEFISS_OWNER.AEFI_TREATMENT_AUD;
CREATE OR REPLACE SYNONYM &USER..AEFI_TREATMENT_ID_SEQ          FOR CAEFISS_OWNER.AEFI_TREATMENT_ID_SEQ;

DEFINE USER=CAEFISS_DL;
CREATE OR REPLACE SYNONYM &USER..AEFI_HOSPITALIZATION           FOR CAEFISS_OWNER.AEFI_HOSPITALIZATION;
CREATE OR REPLACE SYNONYM &USER..AEFI_HOSPITALIZATION_AUD       FOR CAEFISS_OWNER.AEFI_HOSPITALIZATION_AUD;

CREATE OR REPLACE SYNONYM &USER..AEFI_FOLLOW_UP                 FOR CAEFISS_OWNER.AEFI_FOLLOW_UP;
CREATE OR REPLACE SYNONYM &USER..AEFI_FOLLOW_UP_AUD             FOR CAEFISS_OWNER.AEFI_FOLLOW_UP_AUD;
CREATE OR REPLACE SYNONYM &USER..AEFI_FOLLOW_UP_ID_SEQ          FOR CAEFISS_OWNER.AEFI_FOLLOW_UP_ID_SEQ;

CREATE OR REPLACE SYNONYM &USER..AEFI_IMMUNIZATION_ERROR        FOR CAEFISS_OWNER.AEFI_IMMUNIZATION_ERROR;
CREATE OR REPLACE SYNONYM &USER..AEFI_IMMUNIZATION_ERROR_AUD    FOR CAEFISS_OWNER.AEFI_IMMUNIZATION_ERROR_AUD;
CREATE OR REPLACE SYNONYM &USER..AEFI_IMMUNIZATION_ERROR_ID_SEQ FOR CAEFISS_OWNER.AEFI_IMMUNIZATION_ERROR_ID_SEQ;

CREATE OR REPLACE SYNONYM &USER..AEFI_PREVIOUS_AEFI             FOR CAEFISS_OWNER.AEFI_PREVIOUS_AEFI;
CREATE OR REPLACE SYNONYM &USER..AEFI_PREVIOUS_AEFI_AUD         FOR CAEFISS_OWNER.AEFI_PREVIOUS_AEFI_AUD;
CREATE OR REPLACE SYNONYM &USER..AEFI_PREVIOUS_AEFI_ID_SEQ      FOR CAEFISS_OWNER.AEFI_PREVIOUS_AEFI_ID_SEQ;

CREATE OR REPLACE SYNONYM &USER..AEFI_TREATMENT                 FOR CAEFISS_OWNER.AEFI_TREATMENT;
CREATE OR REPLACE SYNONYM &USER..AEFI_TREATMENT_AUD             FOR CAEFISS_OWNER.AEFI_TREATMENT_AUD;
CREATE OR REPLACE SYNONYM &USER..AEFI_TREATMENT_ID_SEQ          FOR CAEFISS_OWNER.AEFI_TREATMENT_ID_SEQ;

SPOOL OFF 
