-- CAF-106: Case Management - Case Deletion & Impact Comments

WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET ECHO ON
SPOOL 12_CAF-106.log
ALTER SESSION SET CURRENT_SCHEMA=CAEFISS_OWNER;

ALTER TABLE AEFI_FORM
ADD (
   QA_PT_CASE_DELETION_COMMENTS VARCHAR2(1000 CHAR),
   QA_IMPACT_TO_MEDICAL_CASE_COMMENTS VARCHAR2(1000 CHAR)
);

ALTER TABLE AEFI_FORM_AUD
ADD (
   QA_PT_CASE_DELETION_COMMENTS VARCHAR2(1000 CHAR),
   QA_IMPACT_TO_MEDICAL_CASE_COMMENTS VARCHAR2(1000 CHAR)
);

commit;

SPOOL OFF
