-- CAF-172: Case Management - Case update table - all changes
-- New fields and updated values for the Case Management - Case Update table

WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET ECHO ON
SPOOL 6_CAF-172.log
ALTER SESSION SET CURRENT_SCHEMA=CAEFISS_OWNER;

-- Add new fields to AEFI_CASE_UPDATE, AEFI_CASE_UPDATE_AUD
ALTER TABLE AEFI_CASE_UPDATE
ADD (
  QA_USERNAME        VARCHAR2(30 CHAR),
  QA_ROLE            VARCHAR2(30 CHAR),
  QA_PRIORITY        NUMBER(5),
  QA_COMMENTS        VARCHAR2(100 CHAR)
 );

ALTER TABLE AEFI_CASE_UPDATE_AUD
ADD (
  QA_USERNAME        VARCHAR2(30 CHAR),
  QA_ROLE            VARCHAR2(30 CHAR),
  QA_PRIORITY        NUMBER(5),
  QA_COMMENTS        VARCHAR2(100 CHAR)
  );
commit;

-- Add constraints to AEFI_CASE_UPDATE 
ALTER TABLE AEFI_CASE_UPDATE
ADD (
  CONSTRAINT FK_AEFI_CASE_UPDATE_QA_PRIORITY FOREIGN KEY(QA_PRIORITY) REFERENCES CD_HIGH_MEDIUM_LOW(ID)
 );
commit;


SPOOL OFF;
