-- CAF-139: Case Management -Assigned to Field - Case issues and resolution - Follow up with reporting jurisdiction
-- This script creates a view that is used as a "wrapper" code table of the SEC_USERS table for fields that need usernames as a lookup

define _APP_USER_ROLE = rl__caefiss_app;
WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET ECHO ON
SPOOL 2_CAF-139.log
ALTER SESSION SET CURRENT_SCHEMA=CAEFISS_OWNER;

-- Model a "users" code table using a view
CREATE OR REPLACE VIEW CD_SEC_USERS_VIEW
    ("ID", "ENGLISH_VALUE", "FRENCH_VALUE", "DATE_CREATED", "USER_CREATED", "DATE_UPDATED", "USER_UPDATED", "STATUS", "VERSION", "SORTORDER")
AS
SELECT 
    ID, 
    USERNAME AS ENGLISH_VALUE,
    USERNAME AS FRENCH_VALUE,
    DATE_CREATED,
    USER_CREATED,
    DATE_UPDATED,
    USER_UPDATED,
    ENABLED AS STATUS,
    VERSION,
    ID AS SORTORDER
FROM SEC_USERS;

-- Added to create-private-synonyms.sql
-- CREATE OR REPLACE SYNONYM CAEFISS_APP.CD_SEC_USERS_VIEW FOR CAEFISS_OWNER.CD_SEC_USERS_VIEW;
GRANT SELECT ON CAEFISS_OWNER.CD_SEC_USERS_VIEW TO &_APP_USER_ROLE;
GRANT SELECT ON CAEFISS_OWNER.CD_SEC_USERS_VIEW TO RL__CAEFISS_LOAD_ETL;


ALTER TABLE AEFI_QA_FOLLOWUP_FPT
ADD (
	ASSIGNED_TO_ID NUMBER(15,0),
    CONSTRAINT FK_AEFI_QA_FOLLOW_FPT_ASSIGNED_TO_ID FOREIGN KEY (ASSIGNED_TO_ID) REFERENCES SEC_USERS (ID)
);

ALTER TABLE AEFI_QA_FOLLOWUP_FPT_AUD
ADD (
    ASSIGNED_TO_ID NUMBER(15,0)
);

ALTER TABLE AEFI_MCR_QA_ISSUES
ADD (
	ASSIGNED_TO_ID NUMBER(15,0),
    CONSTRAINT FK_AEFI_MCR_QA_ISSUES_ASSIGNED_TO_ID FOREIGN KEY (ASSIGNED_TO_ID) REFERENCES SEC_USERS (ID)
);

ALTER TABLE AEFI_MCR_QA_ISSUES_AUD
ADD (
    ASSIGNED_TO_ID NUMBER(15,0)
);


SPOOL OFF
