-- CAF-234: Removing "Pruritis" as a field from all MEDRA tables
-- Disabled the corresponding record

WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET ECHO ON
SPOOL 10_CAF-234.log
ALTER SESSION SET CURRENT_SCHEMA=CAEFISS_OWNER;

UPDATE CAEFISS_OWNER.CD_MEDDRA 
SET STATUS = 0 
WHERE ID = 10037086 AND LLT_CODE = 10037086;

commit;

SPOOL OFF
