-- CAF-171: Case Management - Case Issues and Resolution table - all changes
-- New fields and updated options for the Case Management - Case Issues and Resolution table

WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET ECHO ON
SPOOL 5_CAF-171.log
ALTER SESSION SET CURRENT_SCHEMA=CAEFISS_OWNER;

-- Add new fields to AEFI_MCR_QA_ISSUES, AEFI_MCR_QA_ISSUES_AUD
ALTER TABLE AEFI_MCR_QA_ISSUES
ADD (
  QA_PRIORITY       NUMBER(5),
  MC_REQUIRED       NUMBER(5),
  MC_COMPLETED      NUMBER(5),
  DATE_MC_COMPLETED DATE,
  MC_COMPLETED_BY   VARCHAR2(30 CHAR),
  MCR_REQUIRED       NUMBER(5),
  MCR_COMPLETED      NUMBER(5),
  DATE_MCR_COMPLETED DATE,
  MCR_COMPLETED_BY   VARCHAR2(30 CHAR)
 );

ALTER TABLE AEFI_MCR_QA_ISSUES_AUD
ADD (
  QA_PRIORITY       NUMBER(5),
  MC_REQUIRED       NUMBER(5),
  MC_COMPLETED      NUMBER(5),
  DATE_MC_COMPLETED DATE,
  MC_COMPLETED_BY   VARCHAR2(30 CHAR),
  MCR_REQUIRED       NUMBER(5),
  MCR_COMPLETED      NUMBER(5),
  DATE_MCR_COMPLETED DATE,
  MCR_COMPLETED_BY   VARCHAR2(30 CHAR)
  );
commit;

-- Add constraints to AEFI_MCR_QA_ISSUES
ALTER TABLE AEFI_MCR_QA_ISSUES
ADD (
  CONSTRAINT FK_AEFI_MCR_QA_ISSUES_MC_REQD FOREIGN KEY(MC_REQUIRED) REFERENCES CD_YES_NO(ID), 
  CONSTRAINT FK_AEFI_MCR_QA_ISSUES_MC_COMPLETED FOREIGN KEY(MC_COMPLETED) REFERENCES CD_YES_NO(ID),
  CONSTRAINT FK_AEFI_MCR_QA_ISSUES_MCR_REQD FOREIGN KEY(MCR_REQUIRED) REFERENCES CD_YES_NO(ID),
  CONSTRAINT FK_AEFI_MCR_QA_ISSUES_MCR_COMP FOREIGN KEY(MCR_COMPLETED) REFERENCES CD_FOLLOWUP_FPT_MCR_COMP(ID),
  CONSTRAINT FK_AEFI_MCR_QA_ISSUES_QA_PRIORITY FOREIGN KEY(QA_PRIORITY) REFERENCES CD_HIGH_MEDIUM_LOW(ID)
 );
commit;

-- update table CD_QA_ISSUES_STATUS
INSERT INTO CD_QA_ISSUES_STATUS(ID,ENGLISH_VALUE,FRENCH_VALUE,DATE_CREATED,USER_CREATED,DATE_UPDATED,USER_UPDATED,STATUS,VERSION) VALUES (4,'No corrections needed','Aucune correction nécessaire',sysdate,'Super',null,null,1,0);

-- update table CD_QA_ISSUES_CLASSIFY
UPDATE CD_QA_ISSUES_CLASSIFY
SET ENGLISH_VALUE = 'Internal QA',
    FRENCH_VALUE = 'AQ interne'
WHERE ID = 5;

INSERT INTO CD_QA_ISSUES_CLASSIFY(ID,ENGLISH_VALUE,FRENCH_VALUE,DATE_CREATED,USER_CREATED,DATE_UPDATED,USER_UPDATED,STATUS,VERSION) VALUES (6,'Other','Autre',sysdate,'Super',null,null,1,0);
commit;

SPOOL OFF;
