-- CAF-197: Medical history - Prior COVID-19 infection -new comments field

WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET ECHO ON
SPOOL 8_CAF-197.log
ALTER SESSION SET CURRENT_SCHEMA=CAEFISS_OWNER;

ALTER TABLE AEFI_FORM
ADD (
   MH_COMMENTS_PRIOR_INFECTION VARCHAR2(4000 CHAR)
 );

ALTER TABLE AEFI_FORM_AUD
ADD (
   MH_COMMENTS_PRIOR_INFECTION VARCHAR2(4000 CHAR)
 );

commit;

SPOOL OFF
