-- CAF-173: Medical history - new field
-- Added new field to Medical History

WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET ECHO ON
SPOOL 7_CAF-173.log
ALTER SESSION SET CURRENT_SCHEMA=CAEFISS_OWNER;

ALTER TABLE AEFI_FORM
ADD (
   MH_COMMENTS VARCHAR2(4000 CHAR)
 );

ALTER TABLE AEFI_FORM_AUD
ADD (
   MH_COMMENTS VARCHAR2(4000 CHAR)
 );

commit;

SPOOL OFF
