-- CAF-138: Follow-up with reporting jurisdiction table - new fields
-- Added new fields to the Follow-up with reporting jurisdiction table

define _APP_USER_ROLE = rl__caefiss_app;
WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET ECHO ON
SPOOL 1_CAF-138.log
ALTER SESSION SET CURRENT_SCHEMA=CAEFISS_OWNER;

-- Create code table and code audit table
CREATE TABLE CAEFISS_OWNER.CD_HIGH_MEDIUM_LOW
(
    ID              NUMBER(5),
    ENGLISH_VALUE   VARCHAR2(200 CHAR) not null,
    FRENCH_VALUE    VARCHAR2(200 CHAR) not null,
    DATE_CREATED   DATE not null,
    USER_CREATED    VARCHAR2(30 CHAR) not null,
    DATE_UPDATED    DATE,
    USER_UPDATED    VARCHAR2(30 CHAR),
    STATUS          NUMBER(1) not null,
    VERSION         NUMBER(5) not null,
    SORTORDER       NUMBER(15),
    CONSTRAINT PK_HIGH_MEDIUM_LOW_ID  PRIMARY KEY (ID)
);

CREATE TABLE CAEFISS_OWNER.CD_HIGH_MEDIUM_LOW_AUD
(
    ID              NUMBER(5),
    ENGLISH_VALUE   VARCHAR2(200 CHAR) not null,
    FRENCH_VALUE    VARCHAR2(200 CHAR) not null,
    DATE_CREATED   DATE not null,
    USER_CREATED    VARCHAR2(30 CHAR) not null,
    DATE_UPDATED    DATE,
    USER_UPDATED    VARCHAR2(30 CHAR),
    STATUS          NUMBER(1) not null,
    VERSION         NUMBER(5) not null,
    SORTORDER       NUMBER(15)
);
commit;

-- Insert Code Values
INSERT INTO CD_HIGH_MEDIUM_LOW (ID, ENGLISH_VALUE, FRENCH_VALUE, DATE_CREATED, USER_CREATED, STATUS, VERSION, SORTORDER)
 VALUES(1, 'High','Élevée', SYSDATE, 'SUPER', 1, 0, 10);

INSERT INTO CD_HIGH_MEDIUM_LOW  (ID, ENGLISH_VALUE, FRENCH_VALUE, DATE_CREATED, USER_CREATED, STATUS, VERSION, SORTORDER)
 VALUES(2, 'Medium','Moyenne', SYSDATE, 'SUPER', 1, 0, 20);

INSERT INTO CD_HIGH_MEDIUM_LOW (ID, ENGLISH_VALUE, FRENCH_VALUE, DATE_CREATED, USER_CREATED, STATUS, VERSION, SORTORDER)
 VALUES(3, 'Low','Faible', SYSDATE, 'SUPER', 1, 0, 30);  

INSERT INTO CD_HIGH_MEDIUM_LOW_AUD (ID, ENGLISH_VALUE, FRENCH_VALUE, DATE_CREATED, USER_CREATED, STATUS, VERSION, SORTORDER)
 VALUES(1, 'High','Élevée', SYSDATE, 'SUPER', 1, 0, 10);

INSERT INTO CD_HIGH_MEDIUM_LOW_AUD  (ID, ENGLISH_VALUE, FRENCH_VALUE, DATE_CREATED, USER_CREATED, STATUS, VERSION, SORTORDER)
 VALUES(2, 'Medium','Moyenne', SYSDATE, 'SUPER', 1, 0, 20);

INSERT INTO CD_HIGH_MEDIUM_LOW_AUD (ID, ENGLISH_VALUE, FRENCH_VALUE, DATE_CREATED, USER_CREATED, STATUS, VERSION, SORTORDER)
 VALUES(3, 'Low','Faible', SYSDATE, 'SUPER', 1, 0, 30); 

commit;

-- Create Seq
create sequence HIGH_MEDIUM_LOW_ID_SEQ INCREMENT BY 1 START WITH 10000 CACHE 2;
commit;

-- Permissions
GRANT SELECT, ALTER ON HIGH_MEDIUM_LOW_ID_SEQ TO &_APP_USER_ROLE;

GRANT INSERT, SELECT, UPDATE, DELETE ON CD_HIGH_MEDIUM_LOW TO &_APP_USER_ROLE;

GRANT INSERT, SELECT ON CD_HIGH_MEDIUM_LOW_AUD TO &_APP_USER_ROLE;

GRANT INSERT, SELECT, UPDATE, DELETE ON CAEFISS_OWNER.CD_HIGH_MEDIUM_LOW TO RL__CAEFISS_LOAD_ETL;

GRANT INSERT, SELECT ON CAEFISS_OWNER.CD_HIGH_MEDIUM_LOW_AUD TO RL__CAEFISS_LOAD_ETL;
commit;

-- Add new fields to AEFI_QA_FOLLOWUP_FPT, AEFI_QA_FOLLOWUP_FPT_AUD
ALTER TABLE AEFI_QA_FOLLOWUP_FPT
ADD (
  QA_PRIORITY       NUMBER(5),
  MC_REQUIRED       NUMBER(5),
  MC_COMPLETED      NUMBER(5),
  DATE_MC_COMPLETED DATE,
  MC_COMPLETED_BY   VARCHAR2(30 CHAR)
 );

ALTER TABLE AEFI_QA_FOLLOWUP_FPT_AUD
ADD (
  QA_PRIORITY       NUMBER(5),
  MC_REQUIRED       NUMBER(5),
  MC_COMPLETED      NUMBER(5),
  DATE_MC_COMPLETED DATE,
  MC_COMPLETED_BY   VARCHAR2(30 CHAR)
  );
commit;

-- Add constraints to AEFI_QA_FOLLOWUP_FPT 
ALTER TABLE AEFI_QA_FOLLOWUP_FPT
ADD (
  CONSTRAINT FK_AEFI_QA_FOLLOW_FPT_QA_PRIORITY FOREIGN KEY(QA_PRIORITY) REFERENCES CD_HIGH_MEDIUM_LOW(ID),
  CONSTRAINT FK_AEFI_QA_FOLLOW_FPT_MC_REQD FOREIGN KEY(MC_REQUIRED) REFERENCES CD_YES_NO(ID), 
  CONSTRAINT FK_AEFI_QA_FOLLOW_FPT_MC_COMPLETED FOREIGN KEY(MC_COMPLETED) REFERENCES CD_YES_NO(ID)
 );
commit;

-- update table CD_FOLLOWUP_FPT_QASTATUS
INSERT INTO CD_FOLLOWUP_FPT_QASTATUS  (ID, ENGLISH_VALUE, FRENCH_VALUE, DATE_CREATED, USER_CREATED, STATUS, VERSION, SORTORDER)
 VALUES(5, 'No response received', 'Aucune réponse reçue', SYSDATE, 'SUPER', 1, 0, 50);
 
UPDATE CD_FOLLOWUP_FPT_QASTATUS 
SET ENGLISH_VALUE = 'Request initiated',
    FRENCH_VALUE = 'Demande initiée'
WHERE ID = 3;
commit;

SPOOL OFF;
