-- To create private synonyms for new tables

SET ECHO ON 
SPOOL 11_create-private-synonyms.log 
WHENEVER SQLERROR CONTINUE;

DEFINE USER=CAEFISS_APP;
CREATE OR REPLACE SYNONYM &USER..CD_HIGH_MEDIUM_LOW     FOR CAEFISS_OWNER.CD_HIGH_MEDIUM_LOW;
CREATE OR REPLACE SYNONYM &USER..CD_HIGH_MEDIUM_LOW_AUD FOR CAEFISS_OWNER.CD_HIGH_MEDIUM_LOW_AUD;
CREATE OR REPLACE SYNONYM &USER..CD_SEC_USERS_VIEW      FOR CAEFISS_OWNER.CD_SEC_USERS_VIEW;
CREATE OR REPLACE SYNONYM &USER..CD_AEFI_FIELDS         FOR CAEFISS_OWNER.CD_AEFI_FIELDS;
CREATE OR REPLACE SYNONYM &USER..CD_AEFI_FIELDS_AUD 	FOR CAEFISS_OWNER.CD_AEFI_FIELDS_AUD;

DEFINE USER=CAEFISS_DL;
CREATE OR REPLACE SYNONYM &USER..CD_HIGH_MEDIUM_LOW     FOR CAEFISS_OWNER.CD_HIGH_MEDIUM_LOW;
CREATE OR REPLACE SYNONYM &USER..CD_HIGH_MEDIUM_LOW_AUD FOR CAEFISS_OWNER.CD_HIGH_MEDIUM_LOW_AUD;
CREATE OR REPLACE SYNONYM &USER..CD_SEC_USERS_VIEW      FOR CAEFISS_OWNER.CD_SEC_USERS_VIEW;
CREATE OR REPLACE SYNONYM &USER..CD_AEFI_FIELDS         FOR CAEFISS_OWNER.CD_AEFI_FIELDS;
CREATE OR REPLACE SYNONYM &USER..CD_AEFI_FIELDS_AUD 	FOR CAEFISS_OWNER.CD_AEFI_FIELDS_AUD;

SPOOL OFF 
